### ISSUE TITLE
Can we update the composer requirement to not requiring v0.3.5 of phpseclib?

### ISSUE THREAD

**Issue by yuweizhan** [Vantiv/litle-sdk-for-php#32]
phpseclib's stable version is 2.0.3 now. I'm not sure if supporting newer versions would require any changes on your side, but two major version behind seems really a lot and is probably worth an update. Thanks!

**Comment by squatto** [comment]
There is literally zero reason to have it as a dependency. I've had to fork the repo and create my own version that doesn't require phpseclib, otherwise I can't even use this library (other packages I use refuse to install).

[https://github.com/BlueHelix/litle-sdk-for-php/tree/remove-phpseclib](https://github.com/BlueHelix/litle-sdk-for-php/tree/remove-phpseclib)

**Comment by brianarnold789** [comment]
@yuweizhan,
We updated the requirement for phpseclib to be v2

**Comment by evanernest** [comment]
Can this change be applied to the 8.0 branch?

**Comment by swapnilhande** [comment]
> Can this change be applied to the 8.0 branch?

Released 8.31.2 with the change.

**Comment by squatto** [comment]
Is this going to be pushed to composer?

**Comment by swapnilhande** [comment]
> Is this going to be pushed to composer?

Available in packagist at https://packagist.org/packages/litle/payments-sdk#8.31.2
