### ISSUE TITLE
Dropping support for PHP5

### ISSUE THREAD

**Issue by linuxjuggler** [Vantiv/litle-sdk-for-php#40]
Hey,

Running the tests on PHP 7.1 locally fail because of using `&new` in `Test/functional/SaleFunctionalTest.php on line 302` so is there any plan to drop support for PHP5.x? as PHP 5.3 is dead and not supported any more http://php.net/supported-versions.php

Plus since you guys using PSR-0, why you still have `require_once` statements in your code? https://github.com/Vantiv/litle-sdk-for-php/blob/11.0/litle/sdk/LitleOnlineRequest.php#L27

**Comment by brianarnold789** [comment]
Hi @linuxjuggler, 
We have removed the `&new`, this should help fix the errors in your tests. We maintain support for PHP 5.x because this SDK is also used in the background of out Magento extension and Magento supports PHP 5.

I would have to research the use of `require_once` to make a determination on the impact or removing it in favor of `require`.
Thanks for the feedback!

**Comment by linuxjuggler** [comment]
@brianarnold789 using `require` is not what I meant, I was referring that if you used **PSR4**, composer should be able to load all your classes without even the need to use `require` or `require_once`

Also, I think the same should be with using **PSR0**, which you already use
